import 'package:flutter/material.dart';
import 'app_state.dart';
import 'catalog.dart';

class PlanForm extends StatefulWidget{const PlanForm({super.key,required this.state});final AppState state;@override State<PlanForm> createState()=>_PlanFormState();}
class _PlanFormState extends State<PlanForm>{final title=TextEditingController(),venue=TextEditingController();RevivalCategory? category;DateTime date=DateTime.now();@override Widget build(BuildContext context)=>ListView(padding:const EdgeInsets.all(20),children:[Text('Weekly planning',style:Theme.of(context).textTheme.headlineSmall),const Text('Plans cover Monday–Sunday and are submitted by the configured Wednesday deadline.'),const SizedBox(height:16),TextField(controller:title,decoration:const InputDecoration(labelText:'Activity title *')),const SizedBox(height:12),DropdownButtonFormField<RevivalCategory>(value:category,isExpanded:true,decoration:const InputDecoration(labelText:'Activity category *'),items:widget.state.categories.map((c)=>DropdownMenuItem(value:c,child:Text(c.name))).toList(),onChanged:(v)=>setState(()=>category=v)),const SizedBox(height:12),TextField(controller:venue,decoration:const InputDecoration(labelText:'Venue')),const SizedBox(height:12),ListTile(title:const Text('Activity date'),subtitle:Text(date.toIso8601String().split('T').first),trailing:const Icon(Icons.calendar_month),onTap:()async{final d=await showDatePicker(context:context,firstDate:DateTime.now(),lastDate:DateTime.now().add(const Duration(days:365)),initialDate:date);if(d!=null)setState(()=>date=d);}),FilledButton.icon(onPressed:()async{if(title.text.trim().isEmpty||category==null)return;await widget.state.enqueue('plan',{'title':title.text.trim(),'activity_category_id':category!.id,'activity_category_slug':category!.slug,'event_date':date.toIso8601String().split('T').first,'venue':venue.text.trim()});if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Weekly activity saved to the synchronization queue.')));},icon:const Icon(Icons.save),label:const Text('Save plan'))]);}

class QueuePage extends StatelessWidget{const QueuePage({super.key,required this.state});final AppState state;@override Widget build(BuildContext context)=>ListView(padding:const EdgeInsets.all(16),children:[Row(children:[Expanded(child:Text('Offline queue',style:Theme.of(context).textTheme.headlineSmall)),FilledButton.icon(onPressed:state.sync,icon:const Icon(Icons.sync),label:const Text('Sync now'))]),const SizedBox(height:12),if(state.queue.isEmpty)const Card(child:ListTile(leading:Icon(Icons.check_circle_outline),title:Text('Queue is clear'),subtitle:Text('All records have synchronized.'))),...state.queue.map((q)=>Card(child:ListTile(leading:Icon(q['status']=='failed'?Icons.error_outline:Icons.cloud_upload_outlined),title:Text('${q['type']} • ${q['status']}'),subtitle:Text('${q['created_at']}\n${q['error']??''}'),isThreeLine:true,trailing:PopupMenuButton<String>(onSelected:(v)=>v=='retry'?state.retry('${q['local_id']}'):state.remove('${q['local_id']}'),itemBuilder:(_)=>const[PopupMenuItem(value:'retry',child:Text('Retry')),PopupMenuItem(value:'remove',child:Text('Remove'))]))))]);}

class RegistrationPage extends StatefulWidget{const RegistrationPage({super.key,required this.state});final AppState state;@override State<RegistrationPage> createState()=>_RegistrationPageState();}
class _RegistrationPageState extends State<RegistrationPage>{int step=0;final name=TextEditingController(),email=TextEditingController(),phone=TextEditingController(),region=TextEditingController(),altar=TextEditingController(),bishop=TextEditingController(),password=TextEditingController();String? province,county;String preview='';bool declaration=false;
 @override Widget build(BuildContext context){final forms=[_personal(),_jurisdiction(),_leadership(),_security(),_review()];return Scaffold(appBar:AppBar(title:const Text('Coordinator Registration')),body:Stepper(currentStep:step,onStepContinue:()async{if(step<4){setState(()=>step++);}else{if(!declaration)return;await widget.state.enqueue('registration',{'official_name':name.text.trim(),'email':email.text.trim(),'phone':phone.text.trim(),'province':province,'county':county,'region_display_name':preview,'altar_name':altar.text.trim(),'bishop_name':bishop.text.trim(),'password':password.text});if(mounted)Navigator.pop(context);}},onStepCancel:step==0?null:()=>setState(()=>step--),steps:List.generate(5,(i)=>Step(title:Text(['Personal','Jurisdiction','Leadership','Security','Review'][i]),content:forms[i],isActive:i<=step,state:i<step?StepState.complete:StepState.indexed))));}
 Widget _personal()=>Column(children:[TextField(controller:name,decoration:const InputDecoration(labelText:'Official coordinator name *')),TextField(controller:phone,keyboardType:TextInputType.phone,decoration:const InputDecoration(labelText:'Phone number *')),TextField(controller:email,keyboardType:TextInputType.emailAddress,decoration:const InputDecoration(labelText:'Official email *'))]);
 Widget _jurisdiction()=>Column(children:[DropdownButtonFormField<String>(value:province,decoration:const InputDecoration(labelText:'Province *'),items:provinces.keys.map((p)=>DropdownMenuItem(value:p,child:Text(p))).toList(),onChanged:(v)=>setState((){province=v;county=null;})),DropdownButtonFormField<String>(value:county,decoration:const InputDecoration(labelText:'County *'),items:(province==null?const<String>[]:provinces[province]!).map((c)=>DropdownMenuItem(value:c,child:Text(c))).toList(),onChanged:province==null?null:(v)=>setState(()=>county=v)),TextField(controller:region,decoration:InputDecoration(labelText:'Region base name *',suffixText:'Region',helperText:preview),onChanged:(v){try{setState(()=>preview=formatRegion(v));}catch(e){setState(()=>preview=e.toString().replaceFirst('FormatException: ',''));}}),TextField(controller:altar,decoration:const InputDecoration(labelText:'Altar name *'))]);
 Widget _leadership()=>TextField(controller:bishop,decoration:const InputDecoration(labelText:'Bishop name *'));
 Widget _security()=>TextField(controller:password,obscureText:true,decoration:const InputDecoration(labelText:'Strong password *'));
 Widget _review()=>CheckboxListTile(value:declaration,onChanged:(v)=>setState(()=>declaration=v??false),title:Text('I confirm that the information for ${name.text} is correct and may be verified.'));
}
